language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
before_install:
- openssl aes-256-cbc -K $encrypted_93f59ed2d3dd_key -iv $encrypted_93f59ed2d3dd_iv
  -in .deploy_key.enc -out .deploy_key -d
- chmod 600 .deploy_key