# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Myhero.lt Kauno tvarkaraštis
email:
description: "MyHero.lt tvarkaraščiai"
baseurl: "/myhero" # the subpath of your site, e.g. /blog
url: "http://vaidas.info" # the base hostname & protocol for your site
repo: "vaidas-lungis/myhero"
# Build settings
markdown: kramdown
